name: Deploy and Run Lambda

on:
  workflow_run:
    workflows: ["Zip and Upload to S3"]
    types:
      - completed

jobs:
  deploy-and-run-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name MyGitHubLambdaFunction \
          --s3-bucket api-lambda-artifact \
          --s3-key lambda_function.zip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        mkdir -p package
        pip install -r requirements.txt --target ./package

    - name: Prepare Payload from Event JSON
      run: |
        cat events/event.json
        payload=$(cat events/event.json | jq -c '.')
        echo $payload > payload.json

    - name: Run Lambda Function with Payload
      run: |
        payload=$(jq -c '.' events/event.json)
        echo "Payload: $payload"
        aws lambda invoke \
          --function-name MyGitHubLambdaFunction \
          --payload "$payload" \
          --cli-binary-format raw-in-base64-out \
          response.json
        cat response.json

    - name: Show CloudWatch Logs
      run: |
        aws logs describe-log-groups
        aws logs describe-log-streams --log-group-name /aws/lambda/MyGitHubLambdaFunction
        aws logs get-log-events --log-group-name /aws/lambda/MyGitHubLambdaFunction --log-stream-name $(aws logs describe-log-streams --log-group-name /aws/lambda/MyGitHubLambdaFunction --query "logStreams[0].logStreamName" --output text)
