# .github/workflows/deploy.yaml
name: Zip and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Zip Lambda Function
      run: zip -r lambda_function.zip lambda_function.py

    - name: Upload to S3
      run: |
        aws s3 cp function.zip s3://api-lambda-artifact/lambda_function.zip

