# .github/workflows/deploy.yaml
name: Zip and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Dependencies and zip Lambda Function
      run: |
        mkdir -p package
        pip install -r requirements.txt -t package
        cp lambda_function.py package/
        cp -r src package/
        cp -r tests package/
        cp -r events package/
        cd package
        zip -r ../lambda_function.zip .
        cd ..

    - name: Upload to S3
      run: |
        aws s3 cp lambda_function.zip s3://api-lambda-artifact/lambda_function.zip

