name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Install dependencies (if applicable)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Package the Lambda function
      - name: Zip the Lambda function
        run: zip function.zip lambda_function.py

      # Step 5: Upload to S3
      - name: Upload to S3
        run: aws s3 cp function.zip s3://my-lambda-artifacts/function.zip

      # Step 6: Update the Lambda function
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name MyGitHubLambdaFunction \
            --s3-bucket my-lambda-artifacts \
            --s3-key function.zip
