name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up the programming language (Python in this case)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt

      # Step 4: Linting
      - name: Run Linter (flake8)
        run: |
          flake8 src/ tests/ events/ .github/ lambda_function.py

      # Step 5: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 6: Run Tests
      - name: Run Unit Tests
        env:
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: python3 -m pytest tests/ --junitxml=report.xml