name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up the programming language (Python in this case)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt

      # Step 4: Linting
      - name: Run Linter (flake8)
        run: |
          flake8 src/ tests/ events/ .github/ lambda_function.py

      # Step 5: Run Tests
      - name: Run Unit Tests
        env:
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: python3 -m unittest discover -v tests